name: checstyle

on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: 'testtool'
          workdir: 'src'
          fail_on_error: true
          level: error
          checkstyle_version: 7.1
          checkstyle_config: 'https://raw.githubusercontent.com/wso2/code-quality-tools/master/checkstyle/checkstyle.xml'
