# This is a basic workflow to help you get started with Actions

name: IssueAssigneee

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project-url: "https://github.com/users/tharindu1st/projects/1"
        column-name: "Done"
        label-name: "closed"
        columns-to-ignore: "In Review,Ready to deploy,Done"
